server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
  - url: http://docker-victoria-logs-1:9428/insert/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log
          level:
          app:
          env:
          component:
    pipeline_stages:
      - logfmt:
          mapping:
           component:
           level:
           app:
      - labels:
          component:
          level:
          app:
          env: